export const searchData = [
   // --- PAGES ---
   {
      id: 1,
      title: 'Home',
      category: 'Page',
      type: 'page',
      href: '/',
      image: null,
      keywords: ['home', 'main', 'ana sayfa'],
   },
   {
      id: 2,
      title: 'About Us',
      category: 'Page',
      type: 'page',
      href: '/about-us',
      image: null,
      keywords: ['about', 'hakkında', 'ozlem', 'bicer', 'doctor'],
   },
   {
      id: 3,
      title: 'Dr. Özlem Bicer',
      category: 'About Us',
      type: 'page',
      href: '/about-us/dr-ozlem-bicer',
      image: null,
      keywords: ['doctor', 'doktor', 'ozlem', 'bicer', 'surgeon'],
   },
   {
      id: 4,
      title: 'Clinic & Team',
      category: 'About Us',
      type: 'page',
      href: '/about-us/clinic-team',
      image: null,
      keywords: ['clinic', 'team', 'staff', 'klinik', 'ekip'],
   },
   {
      id: 5,
      title: 'Pricing',
      category: 'About Us',
      type: 'page',
      href: '/about-us/pricing',
      image: null,
      keywords: ['price', 'pricing', 'fiyat', 'cost', 'fee'],
   },
   {
      id: 6,
      title: 'Hair Loss',
      category: 'Page',
      type: 'page',
      href: '/hair-loss',
      image: null,
      keywords: ['hair loss', 'saç dökülmesi', 'alopecia'],
   },
   {
      id: 7,
      title: 'Hair Loss in Male',
      category: 'Hair Loss',
      type: 'page',
      href: '/hair-loss/couses-of-hair-loss/male-hair-loss',
      image: null,
      keywords: ['male', 'erkek', 'hair loss', 'saç dökülmesi', 'men'],
   },
   {
      id: 8,
      title: 'Hair Loss in Female',
      category: 'Hair Loss',
      type: 'page',
      href: '/hair-loss/couses-of-hair-loss/female-hair-loss',
      image: null,
      keywords: ['female', 'kadın', 'hair loss', 'saç dökülmesi', 'women'],
   },
   {
      id: 9,
      title: 'Hair Mesotherapy',
      category: 'Treatments',
      type: 'page',
      href: '/hair-loss/treatments-of-hair-loss/hair-mesotherapy',
      image: null,
      keywords: ['mesotherapy', 'mezoterapi', 'treatment', 'tedavi'],
   },
   {
      id: 10,
      title: 'PRP Hair Treatment',
      category: 'Treatments',
      type: 'page',
      href: '/hair-loss/treatments-of-hair-loss/prp-hair-treatment',
      image: null,
      keywords: ['prp', 'treatment', 'tedavi', 'platelet'],
   },
   {
      id: 11,
      title: 'Stamp Cell Treatment',
      category: 'Treatments',
      type: 'page',
      href: '/hair-loss/treatments-of-hair-loss/stamp-cell-treatment',
      image: null,
      keywords: ['stamp cell', 'stem cell', 'kök hücre', 'treatment'],
   },
   {
      id: 12,
      title: 'Trichopat Treatment',
      category: 'Treatments',
      type: 'page',
      href: '/hair-loss/treatments-of-hair-loss/trichopat-treatment',
      image: null,
      keywords: ['trichopat', 'treatment', 'tedavi'],
   },
   {
      id: 13,
      title: 'Hair Transplant',
      category: 'Transplantation',
      type: 'page',
      href: '/hair-transplant',
      image: null,
      keywords: ['hair transplant', 'saç ekimi', 'fue', 'fut'],
   },
   {
      id: 14,
      title: 'FUE (Micro Motor)',
      category: 'Hair Transplant',
      type: 'page',
      href: '/hair-transplant#fue-micro-motor',
      image: null,
      keywords: ['fue', 'micro motor', 'hair transplant', 'saç ekimi'],
   },
   {
      id: 15,
      title: 'FUE (Manuel)',
      category: 'Hair Transplant',
      type: 'page',
      href: '/hair-transplant#fue-manuel',
      image: null,
      keywords: ['fue', 'manuel', 'manual', 'hair transplant'],
   },
   {
      id: 16,
      title: 'Body Hair Transplantation',
      category: 'Hair Transplant',
      type: 'page',
      href: '/hair-transplant#body-hair-transplant',
      image: null,
      keywords: ['body hair', 'bht', 'transplant', 'saç ekimi'],
   },
   {
      id: 17,
      title: 'Reconstructive Hair Transplant',
      category: 'Hair Transplant',
      type: 'page',
      href: '/hair-transplant#reconstructive-hair-transplant',
      image: null,
      keywords: ['reconstructive', 'rekonstrüktif', 'repair', 'hair transplant'],
   },
   {
      id: 18,
      title: 'Long Hair (Unshaven)',
      category: 'Hair Transplant',
      type: 'page',
      href: '/hair-transplant#long-hair',
      image: null,
      keywords: ['long hair', 'unshaven', 'uzun saç', 'hair transplant'],
   },
   {
      id: 19,
      title: 'FUT',
      category: 'Hair Transplant',
      type: 'page',
      href: '/hair-transplant#fut',
      image: null,
      keywords: ['fut', 'follicular unit', 'strip', 'hair transplant'],
   },
   {
      id: 20,
      title: 'Beard Transplantation',
      category: 'Transplantation',
      type: 'page',
      href: '/beard-transplantation',
      image: null,
      keywords: ['beard', 'sakal', 'transplant', 'ekimi'],
   },
   {
      id: 21,
      title: 'Eyebrow Transplant',
      category: 'Transplantation',
      type: 'page',
      href: '/eyebrown-transplant',
      image: null,
      keywords: ['eyebrow', 'kaş', 'transplant', 'ekimi'],
   },
   {
      id: 22,
      title: 'Gallery',
      category: 'Page',
      type: 'page',
      href: '/gallery',
      image: null,
      keywords: ['gallery', 'galeri', 'video', 'photos', 'results'],
   },
   {
      id: 23,
      title: 'Before & After Images',
      category: 'Gallery',
      type: 'page',
      href: '/gallery/before-after-images',
      image: null,
      keywords: ['gallery', 'galeri', 'before after', 'önce sonra', 'results', 'photos'],
   },
   {
      id: 24,
      title: 'Causes of Hair Loss',
      category: 'Hair Loss',
      type: 'page',
      href: '/hair-loss/couses-of-hair-loss',
      image: null,
      keywords: ['causes', 'nedenler', 'hair loss', 'saç dökülmesi'],
   },
   {
      id: 25,
      title: 'Treatments of Hair Loss',
      category: 'Hair Loss',
      type: 'page',
      href: '/hair-loss/treatments-of-hair-loss',
      image: null,
      keywords: ['treatment', 'tedavi', 'hair loss', 'saç dökülmesi'],
   },
   {
      id: 26,
      title: 'Guides',
      category: 'Page',
      type: 'page',
      href: '/guides',
      image: null,
      keywords: ['guide', 'rehber', 'instructions', 'talimat'],
   },
   {
      id: 27,
      title: 'Before Hair Transplantation',
      category: 'Guides',
      type: 'page',
      href: '/guides/before-hair-transplantation',
      image: null,
      keywords: ['before', 'öncesi', 'guide', 'rehber', 'hair transplant', 'saç ekimi'],
   },
   {
      id: 28,
      title: 'After Hair Transplantation',
      category: 'Guides',
      type: 'page',
      href: '/guides/after-hair-transplantation',
      image: null,
      keywords: ['after', 'sonrası', 'guide', 'rehber', 'hair transplant', 'saç ekimi'],
   },
   {
      id: 29,
      title: 'Contact Us',
      category: 'Page',
      type: 'page',
      href: '/contact-us',
      image: null,
      keywords: ['contact', 'iletişim', 'email', 'phone', 'appointment', 'randevu'],
   },
];
