import localFont from 'next/font/local';
import "../globals.css";
import { hasLocale, NextIntlClientProvider } from "next-intl";
import { routing } from "@/i18n/routing";
import { notFound } from "next/navigation";
import Header from "@/components/header";
import Footer from "@/components/footer";
import { ReactLenis } from "@/lib/lenis";

const inter = localFont({
  src: [
    { path: "../../fonts/Inter-ExtraLight.woff2", weight: "200", style: "normal" },
    { path: "../../fonts/Inter-Light.woff2", weight: "300", style: "normal" },
    { path: "../../fonts/Inter-Regular.woff2", weight: "400", style: "normal" },
    { path: "../../fonts/Inter-Medium.woff2", weight: "500", style: "normal" },
    { path: "../../fonts/Inter-SemiBold.woff2", weight: "600", style: "normal" },
    { path: "../../fonts/Inter-Bold.woff2", weight: "700", style: "normal" },
    { path: "../../fonts/Inter-ExtraBold.woff2", weight: "800", style: "normal" },
    { path: "../../fonts/Inter-Black.woff2", weight: "900", style: "normal" },
  ],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }) {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body className={`${inter.variable} font-inter antialiased w-full bg-stone-beige`}>
        <NextIntlClientProvider>
          <ReactLenis root options={{ smoothWheel: true }}>
            <Header />
            <div className='pt-20 sm:pt-25 lg:pt-30'>{children}</div>
            {/* {children} */}
            <Footer />
          </ReactLenis>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
